# Generated by Django 6.0.3 on 2026-03-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("opening_time", models.TimeField(default="08:00:00")),
                ("closing_time", models.TimeField(default="21:00:00")),
            ],
        ),
    ]
