# Generated by Django 6.0.2 on 2026-03-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
