# Generated by Django 6.0.2 on 2026-02-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Hotline')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ (Lat)')),
                ('longitude', models.FloatField(verbose_name='Kinh độ (Lon)')),
            ],
        ),
    ]
