# Generated by Django 6.0.2 on 2026-03-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Hình ảnh cửa hàng'),
        ),
    ]
