# Generated by Django 6.0.3 on 2026-03-15 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_order_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Số lượng thay đổi")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("in", "Nhập kho"), ("out", "Xuất kho")],
                        max_length=3,
                        verbose_name="Loại giao dịch",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú/Lý do"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian thực hiện"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="core.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thực hiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch kho",
                "verbose_name_plural": "Lịch sử giao dịch kho",
                "ordering": ["-created_at"],
            },
        ),
    ]
