# Generated by Django 6.0.3 on 2026-03-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_stocktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Giá nhập đơn vị",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="store_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.store",
                verbose_name="Cửa hàng nhận",
            ),
        ),
    ]
