# Generated by Django 6.0.3 on 2026-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bài viết giới thiệu"
            ),
        ),
    ]
