# Generated by Django 6.0.3 on 2026-03-30 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_product_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stores",
        ),
        migrations.AddField(
            model_name="store",
            name="closing_time",
            field=models.TimeField(default="21:00:00", verbose_name="Giờ đóng cửa"),
        ),
        migrations.AddField(
            model_name="store",
            name="opening_time",
            field=models.TimeField(default="08:00:00", verbose_name="Giờ mở cửa"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                unique=True, verbose_name="Đường dẫn thân thiện (URL)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày đặt hàng"),
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="Họ và tên người nhận"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ xử lý"),
                    ("processing", "Đang đóng gói"),
                    ("shipped", "Đang giao hàng"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Trạng thái đơn",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="Tổng tiền hóa đơn"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.order",
                verbose_name="Thuộc đơn hàng",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="Giá lúc mua"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Số lượng"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.category",
                verbose_name="Danh mục",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bài viết giới thiệu chi tiết"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Mô tả tóm tắt (Thông số kỹ thuật)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Ảnh đại diện (Bìa)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                default=0, verbose_name="Số lượng tồn kho hiện tại"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/gallery/", verbose_name="Hình ảnh"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Giá nhập đơn vị (Nếu là Nhập kho)",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_history",
                to="core.product",
                verbose_name="Sản phẩm giao dịch",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="store_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.store",
                verbose_name="Cửa hàng nhận (Nếu là Xuất kho)",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("in", "Nhập kho"), ("out", "Xuất kho")],
                max_length=3,
                verbose_name="Loại giao dịch (Nhập/Xuất)",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nhân viên thực hiện",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Địa chỉ chi tiết"),
        ),
        migrations.AlterField(
            model_name="store",
            name="latitude",
            field=models.FloatField(verbose_name="Vĩ độ (Latitude)"),
        ),
        migrations.AlterField(
            model_name="store",
            name="longitude",
            field=models.FloatField(verbose_name="Kinh độ (Longitude)"),
        ),
        migrations.AlterField(
            model_name="store",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Hotline"
            ),
        ),
    ]
