# Generated by Django 6.0.3 on 2026-04-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0, verbose_name="Tồn kho tại chi nhánh"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_stocks",
                        to="core.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="core.store",
                        verbose_name="Cửa hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tồn kho chi nhánh",
                "verbose_name_plural": "Tồn kho các chi nhánh",
                "unique_together": {("store", "product")},
            },
        ),
    ]
