# Generated by Django 6.0.3 on 2026-04-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_storestock"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flash_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Giá Flash Sale (VNĐ)",
                    ),
                ),
                ("end_time", models.DateTimeField(verbose_name="Thời gian kết thúc")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Trạng thái kích hoạt"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_sale",
                        to="core.product",
                        verbose_name="Sản phẩm áp dụng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chương trình Flash Sale",
                "verbose_name_plural": "Các chương trình Flash Sale",
            },
        ),
    ]
