# Generated by Django 6.0.3 on 2026-04-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_flashsale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã giảm giá"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Phần trăm (%)"),
                            ("fixed", "Tiền mặt (VNĐ)"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="Loại giảm giá",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Giá trị giảm"
                    ),
                ),
                (
                    "min_purchase",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Đơn hàng tối thiểu",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Ngày bắt đầu")),
                ("valid_to", models.DateTimeField(verbose_name="Ngày kết thúc")),
                (
                    "usage_limit",
                    models.IntegerField(
                        default=100, verbose_name="Giới hạn số lượt dùng"
                    ),
                ),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="Số lượt đã dùng"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Trạng thái"),
                ),
            ],
            options={
                "verbose_name": "Mã giảm giá",
                "verbose_name_plural": "Các mã giảm giá",
            },
        ),
    ]
