# Generated by Django 6.0.3 on 2026-04-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_order_coupon_order_discount_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="store",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_spent",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
