# Generated by Django 6.0.3 on 2026-04-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_userprofile_role_remove_userprofile_store_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Khách hàng"),
                    ("staff", "Nhân viên"),
                    ("store_admin", "Quản lý cửa hàng"),
                    ("super_admin", "Quản trị viên hệ thống"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="core.store",
            ),
        ),
    ]
