# Generated by Django 6.0.3 on 2026-04-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_userprofile_role_userprofile_store"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Hồ sơ người dùng",
                "verbose_name_plural": "Hồ sơ người dùng",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Ảnh đại diện"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Số điện thoại"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Điểm tích lũy"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Admin Tổng"),
                    ("store_admin", "Quản lý Cửa hàng"),
                    ("staff", "Nhân viên"),
                    ("customer", "Khách hàng"),
                ],
                default="customer",
                max_length=20,
                verbose_name="Vai trò",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="core.store",
                verbose_name="Trực thuộc cửa hàng",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_spent",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="Tổng chi tiêu"
            ),
        ),
    ]
