# Generated by Django 6.0.3 on 2026-04-08 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_shippingaddress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={
                "ordering": ["-is_default", "-id"],
                "verbose_name": "Địa chỉ nhận hàng",
                "verbose_name_plural": "Sổ địa chỉ khách hàng",
            },
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="address_detail",
            field=models.TextField(verbose_name="Địa chỉ chi tiết"),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="area_info",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Khu vực (Tỉnh/Huyện/Xã)",
            ),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Địa chỉ mặc định"),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Số điện thoại"),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="receiver_name",
            field=models.CharField(max_length=100, verbose_name="Tên người nhận"),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
    ]
