# Generated by Django 6.0.3 on 2026-04-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_shippingaddress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_main_warehouse",
            field=models.BooleanField(
                default=False, verbose_name="Là Kho Tổng (Trung tâm)"
            ),
        ),
    ]
