# Generated by Django 6.0.3 on 2026-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_order_fulfillment_store_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_stock_deducted",
            field=models.BooleanField(default=False, verbose_name="Đã trừ kho"),
        ),
    ]
