# Generated by Django 6.0.3 on 2026-04-11 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_order_is_stock_deducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='Số sao (1-5)')),
                ('comment', models.TextField(verbose_name='Nội dung đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng bình luận')),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'verbose_name_plural': 'Đánh giá sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
