# Generated by Django 6.0.3 on 2026-04-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Phúc đáp từ cửa hàng'),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phúc đáp'),
        ),
    ]
