# Generated by Django 6.0.3 on 2026-04-16 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_review_admin_reply_review_reply_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email liên hệ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('topic', models.CharField(choices=[('product', 'Hỏi về sản phẩm'), ('order', 'Hỏi về đơn hàng'), ('warranty', 'Bảo hành / Sửa chữa'), ('shipping', 'Vận chuyển / Giao hàng'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Chủ đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('read', 'Đã đọc'), ('replied', 'Đã phản hồi')], default='new', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản (nếu có)')),
            ],
            options={
                'verbose_name': 'Ý kiến khách hàng',
                'verbose_name_plural': 'Ý kiến khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
