# Generated by Django 6.0.3 on 2026-04-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí giao hàng'),
        ),
    ]
