# Generated by Django 6.0.3 on 2026-04-19 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_shipping_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang đóng gói'), ('shipped', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('returned', 'Đã trả hàng'), ('delivery_failed', 'Giao hàng thất bại')], default='pending', max_length=20, verbose_name='Trạng thái đơn'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Lý do trả hàng')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='returns/', verbose_name='Ảnh bằng chứng')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt - Chờ nhận hàng'), ('completed', 'Đã hoàn tiền & Nhập kho lỗi'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('refund_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền sẽ hoàn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi yêu cầu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng trả')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DefectiveProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Tồn kho hàng lỗi/cũ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defective_stocks', to='core.product', verbose_name='Sản phẩm')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defective_inventory', to='core.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Tồn kho hàng lỗi/cũ',
                'verbose_name_plural': 'Tồn kho hàng lỗi/cũ các chi nhánh',
                'unique_together': {('store', 'product')},
            },
        ),
    ]
