# Generated by Django 6.0.3 on 2026-04-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_order_status_returnrequest_returnitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán tiền mặt khi nhận hàng (COD)'), ('bank_transfer', 'Chuyển khoản ngân hàng')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Ảnh biên lai (nếu check bank)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
    ]
