# Generated by Django 6.0.3 on 2026-04-19 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_order_payment_method_order_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_chosen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Màu đã chọn'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='storage_chosen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dung lượng đã chọn'),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Màu sắc')),
                ('storage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dung lượng bộ nhớ')),
                ('additional_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá cộng thêm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='core.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Các biến thể sản phẩm',
            },
        ),
        migrations.AlterUniqueTogether(
            name='defectiveproductstock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='storestock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='defectiveproductstock',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productvariation', verbose_name='Biến thể'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productvariation', verbose_name='Phân loại đã đặt'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productvariation', verbose_name='Biến thể giao dịch'),
        ),
        migrations.AddField(
            model_name='storestock',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productvariation', verbose_name='Biến thể'),
        ),
        migrations.AlterUniqueTogether(
            name='defectiveproductstock',
            unique_together={('store', 'product', 'variation')},
        ),
        migrations.AlterUniqueTogether(
            name='storestock',
            unique_together={('store', 'product', 'variation')},
        ),
    ]
