# Generated by Django 6.0.2 on 2026-04-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_orderitem_color_chosen_orderitem_storage_chosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả cửa hàng'),
        ),
    ]
