# Generated by Django 6.0.3 on 2026-05-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_store_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storestock',
            name='reserved_quantity',
            field=models.IntegerField(default=0, verbose_name='Hàng tạm giữ (Reserved)'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Nhập kho (Nhập mới)'), ('out', 'Xuất kho (Điều chuyển)'), ('sale', 'Xuất bán hàng (Đơn hàng)'), ('return', 'Nhập trả hàng lỗi'), ('restock', 'Hoàn kho (Giao thất bại)'), ('transfer_out', 'Xuất điều chuyển đi'), ('transfer_in', 'Nhận điều chuyển đến')], max_length=20, verbose_name='Loại giao dịch'),
        ),
        migrations.AlterField(
            model_name='storestock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Tồn kho thực tế (Physical)'),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã phiếu')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt xuất'), ('shipping', 'Đang vận chuyển'), ('completed', 'Đã nhận hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất kho')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhận hàng')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt xuất')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.store', verbose_name='Từ kho')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận hàng')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.store', verbose_name='Đến kho')),
            ],
            options={
                'verbose_name': 'Phiếu điều chuyển kho',
                'verbose_name_plural': 'Các phiếu điều chuyển kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng điều chuyển')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Sản phẩm')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.stocktransfer')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productvariation', verbose_name='Biến thể')),
            ],
        ),
    ]
