# Generated by Django 6.0.3 on 2026-05-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_storestock_reserved_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Nhập kho (Nhập mới)'), ('out', 'Xuất kho (Điều chuyển)'), ('sale', 'Xuất bán hàng (Đơn hàng)'), ('return', 'Nhập trả hàng lỗi'), ('restock', 'Hoàn kho (Giao thất bại)'), ('transfer_out', 'Xuất điều chuyển đi'), ('transfer_in', 'Nhận điều chuyển đến'), ('inventory_loss', 'Xuất cân bằng kho (Hao hụt)'), ('inventory_gain', 'Nhập cân bằng kho (Dư thừa)')], max_length=20, verbose_name='Loại giao dịch'),
        ),
        migrations.CreateModel(
            name='Stocktaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã phiếu kiểm kê')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp / Đang đếm'), ('approved', 'Đã duyệt / Đã cân bằng'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stocktakings', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stocktakings', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktakings', to='core.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Phiếu kiểm kê',
                'verbose_name_plural': 'Các phiếu kiểm kê',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(verbose_name='Tồn kho phần mềm')),
                ('actual_quantity', models.IntegerField(verbose_name='Tồn kho thực tế (đếm tay)')),
                ('discrepancy', models.IntegerField(default=0, verbose_name='Chênh lệch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Sản phẩm')),
                ('stocktaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.stocktaking')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productvariation', verbose_name='Biến thể')),
            ],
        ),
    ]
