# Generated by Django 6.0.3 on 2026-05-04 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_stocktransaction_transaction_type_stocktaking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên khu vực')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Khu vực',
                'verbose_name_plural': 'Các khu vực',
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_main_warehouse',
        ),
        migrations.AddField(
            model_name='store',
            name='is_warehouse',
            field=models.BooleanField(default=False, verbose_name='Là Kho hàng khu vực (Không bán lẻ)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Admin Toàn Quốc'), ('regional_manager', 'Quản lý Vùng'), ('store_admin', 'Quản lý Cửa hàng'), ('warehouse_keeper', 'Thủ kho'), ('sales_staff', 'Nhân viên bán hàng'), ('customer', 'Khách hàng')], default='customer', max_length=20, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.store', verbose_name='Trực thuộc cửa hàng/kho'),
        ),
        migrations.AddField(
            model_name='store',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='core.region', verbose_name='Thuộc khu vực'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='core.region', verbose_name='Quản lý khu vực (Dành cho Quản lý vùng)'),
        ),
    ]
