# Generated by Django 6.0.3 on 2026-05-04 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_region_remove_store_is_main_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Danh mục tin tức',
                'verbose_name_plural': 'Các danh mục tin tức',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='Ảnh đại diện (Thumbnail)')),
                ('short_description', models.TextField(verbose_name='Mô tả ngắn')),
                ('content', models.TextField(verbose_name='Nội dung bài viết')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.newscategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết tin tức',
                'verbose_name_plural': 'Các bài viết tin tức',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bình luận')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.newsarticle', verbose_name='Bài viết')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Bình luận tin tức',
                'verbose_name_plural': 'Các bình luận tin tức',
                'ordering': ['-created_at'],
            },
        ),
    ]
