# Generated by Django 6.0.3 on 2026-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_newscategory_newsarticle_newscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên sự kiện')),
                ('event_date', models.DateField(verbose_name='Ngày diễn ra')),
                ('location', models.CharField(max_length=255, verbose_name='Địa điểm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sự kiện',
                'verbose_name_plural': 'Các sự kiện',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề video')),
                ('youtube_url', models.URLField(verbose_name='Link YouTube')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video YouTube',
                'verbose_name_plural': 'Các video YouTube',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Bài viết tin tức', 'verbose_name_plural': 'Các bài viết tin tức'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Ghim bài viết'),
        ),
    ]
