# Generated by Django 6.0.3 on 2026-05-07 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_event_youtubevideo_alter_newsarticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.newsarticle', verbose_name='Bài viết liên kết'),
        ),
    ]
