"""
Django settings for webbanhang project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c@x^+og_+hu^!l%+-=v0t(+913&4=$0=^jya)cvpnqu*h24i#^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG =False 
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'apps.client',
    'apps.admin_panel',
    'apps.core',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webbanhang.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.client.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'webbanhang.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bandienthoai_db2',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import os

import os

# Đường dẫn gốc của OSGeo4W
OSGEO4W_ROOT = r'C:\OSGeo4W'

# Thêm đường dẫn bin vào PATH của hệ thống để nhận diện các file .dll phụ thuộc
os.environ['PATH'] = os.path.join(OSGEO4W_ROOT, 'bin') + os.path.pathsep + os.environ['PATH']
os.environ['PROJ_LIB'] = os.path.join(OSGEO4W_ROOT, 'share', 'proj')

# Chỉ định đường dẫn thư viện GDAL - HÃY KIỂM TRA TÊN FILE TRONG THƯ MỤC BIN
# Ví dụ nếu bạn thấy file gdal310.dll thì sửa thành 'gdal310.dll'
GDAL_LIBRARY_PATH = os.path.join(OSGEO4W_ROOT, 'bin', 'gdal310.dll')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ============================================================
# CẤU HÌNH EMAIL
# ============================================================

# --- CHẾ ĐỘ TEST (Mailtrap Sandbox) ---
# Email bị "bẫy" vào Mailtrap, KHÔNG đến email thật người dùng.
# Bỏ comment block dưới nếu muốn quay lại test:
#
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '18f20f705bf57c'
EMAIL_HOST_PASSWORD = 'a8ee96c8953a56'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'noreply@phonestore.vn'

# --- CHẾ ĐỘ PRODUCTION (Gmail SMTP - Gửi email thật) ---
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'phuctran212005@gmail.com'
# EMAIL_HOST_PASSWORD = 'vzby sacc cjem kuop'
# DEFAULT_FROM_EMAIL = 'Phone Store <phuctran212005@gmail.com>'
# ADMIN_EMAIL = 'phuctran212005@gmail.com'  # Email nhận thông báo ý kiến khách hàng

# ============================================================
# CẤU HÌNH AI (GROQ)
# ============================================================
